<script setup lang="ts">
import {
  IconCards,
  IconPlayerPlay,
  IconLayoutDashboard,
  IconUser,
  IconChartBar,
  IconTrophy,
  IconPalette,
  IconSettings,
  IconLogout,
  IconPlus,
  IconArrowRight,
  IconArrowLeft,
  IconCopy,
  IconLink,
  IconCheck,
  IconX,
  IconUsers,
  IconLock,
  IconVolume,
  IconChevronRight,
  IconWifi,
  IconWifiOff,
  IconMenu2,
  IconBrandGithub,
  IconSparkles,
  IconStar,
  IconDiamond,
  IconFlame,
  IconSwords,
  IconTarget,
  IconShieldCheck,
  IconRoute,
  IconCoins,
} from '@tabler/icons-vue'
const icons = {
  cards: IconCards,
  play: IconPlayerPlay,
  dashboard: IconLayoutDashboard,
  user: IconUser,
  stats: IconChartBar,
  trophy: IconTrophy,
  collection: IconPalette,
  settings: IconSettings,
  logout: IconLogout,
  plus: IconPlus,
  arrow: IconArrowRight,
  back: IconArrowLeft,
  copy: IconCopy,
  link: IconLink,
  check: IconCheck,
  close: IconX,
  users: IconUsers,
  lock: IconLock,
  volume: IconVolume,
  chevron: IconChevronRight,
  connected: IconWifi,
  disconnected: IconWifiOff,
  menu: IconMenu2,
  github: IconBrandGithub,
  sparkles: IconSparkles,
  star: IconStar,
  diamond: IconDiamond,
  flame: IconFlame,
  swords: IconSwords,
  target: IconTarget,
  shield: IconShieldCheck,
  route: IconRoute,
  coins: IconCoins,
}
withDefaults(defineProps<{ name: keyof typeof icons; size?: number }>(), { size: 20 })
</script>
<template><component :is="icons[name]" :size="size" stroke="1.7" aria-hidden="true" /></template>
